### ISSUE TITLE
Deploy to GH Pages & Create Action to dynamically create Preview for PRs.

### ISSUE THREAD

**Issue by Cameron-Porter** [Vets-Who-Code/romeo-golf-cohort#43]
# Description

As a contributor, I want to have the ability to see a preview of a PR when changes have been made vs pull locally to test.

### Acceptance Criteria

- [x] [Deploy repo to GH Pages](https://betterprogramming.pub/how-to-host-your-react-app-on-github-pages-for-free-919ad201a4cb)
- [x] [Implement GH Action](https://github.com/rossjrw/pr-preview-action)

### Time Investment

- Backend: 30min

### Business Sense

- This update will expedite the reviewing process. Allowing for reviewers to take less time with trivial tasks and spend more time reviewing and coding for quality.

**Comment by rmrose78** [comment]
Comment test
